spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.56.10:3306/gulimall_pms
    username: root
    password: root
  # nacos注册中心配置
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
#    alicloud:  都放在third-party模块里
#      access-key: LTAI5tEmjWJmidi9c3YTseRf
#      secret-key: ZmoZ8IDnA4ObqWkwfk7QIR0ewaAQMs
#      oss:
#        endpoint: oss-eu-central-1.aliyuncs.com
  application:
    name: gulimall-product
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  thymeleaf:
    cache: false
  redis:
    host: 192.168.56.10
    port: 6379
  cache:
    type: redis
    redis:
      time-to-live: 3600000
      key-prefix: CACHE_
      cache-null-values: true # 缓存null值，防止缓存穿透
      use-key-prefix: true

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  # 只扫描自己类下的mapper，告诉mybatis-plus sql映射文件的位置
  global-config:
    db-config:
      id-type: auto # 自增主键
      # 配置全局的逻辑删除规则（可省略）
      logic-delete-value: 1
      logic-not-delete-value: 0

server:
  port: 10000

logging:
  level:
    com.zitao.gulimall: debug

# 自定义线程池参数
gulimall:
  thread:
    corePoolSize: 10
    maxPoolSize: 20
    keepAliveTime: 300
