spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: gulimall-auth-server
  redis:
    host: 192.168.56.10
    port: 6379

server:
  port: 20000

logging:
  level:
    com.zitao.gulimall: debug

