spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: gulimall-search
  thymeleaf:
    cache: false
  session:
    store-type: redis
  redis:
    port: 6379
    host: 192.168.56.10


server:
  port: 12000

logging:
  level:
    com.zitao.gulimall: debug

