spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: LTAI5tEmjWJmidi9c3YTseRf
      secret-key: ZmoZ8IDnA4ObqWkwfk7QIR0ewaAQMs
      oss:
        endpoint: oss-eu-central-1.aliyuncs.com
        bucket: gulimall-zitao
      sms:
        host: https://dfsns.market.alicloudapi.com/data/send_sms
        path: /sms/
        templateId: 1
        appcode: ec9afc62a5c04c2b9ecb3aafa9fc05d4
  application:
    name: gulimall-third-party

server:
  port: 30000

logging:
  level:
    com.zitao.gulimall: debug

