spring:
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8333
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: LTAI5tEmjWJmidi9c3YTseRf
      secret-key: ZmoZ8IDnA4ObqWkwfk7QIR0ewaAQMs
      oss:
        endpoint: oss-eu-central-1.aliyuncs.com
        bucket: gulimall-zitao
      sms:
        host: https://dfsns.market.alicloudapi.com
        path: /data/send_sms
        templateId: TPL_0000
        appcode: ec9afc62a5c04c2b9ecb3aafa9fc05d4
  application:
    name: gulimall-third-party
  zipkin:
    base-url: http://192.168.56.10:9411/
    sender:
      type: web
    discovery-client-enabled: false

  sleuth:
    sampler:
      probability: 1

server:
  port: 30000

logging:
  level:
    com.zitao.gulimall: debug

management:
  endpoints:
    web:
      exposure:
        include: '*'

