spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.56.10:3306/gulimall_wms
    username: root
    password: root
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: localhost:8333
  application:
    name: gulimall-ware
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  rabbitmq:
    host: 192.168.56.10
    username: guest
    password: guest
    listener:
      simple:
        acknowledge-mode: manual
  zipkin:
    base-url: http://192.168.56.10:9411/
    sender:
      type: web
    discovery-client-enabled: false

  sleuth:
    sampler:
      probability: 1

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml  #只扫描自己类下的mapper
  global-config:
    db-config:
      id-type: auto # 自增主键

server:
  port: 11000

logging:
  level:
    com.zitao.gulimall: debug

management:
  endpoints:
    web:
      exposure:
        include: '*'